### ISSUE TITLE
Prometheus crashing Nginx Ingress

### ISSUE THREAD

**Issue by felipe-augusto** [poseidon/typhoon#163] opened 2018-03-19 11:59 UTC
### Environment

* Platform: digital-ocean
* OS: container-linux
* Terraform: `v0.11.3`

### Problem

I am having a problem with Prometheus and Nginx Ingress working together.
For some reason, after I installed Prometheus following this tutorial `https://typhoon.psdn.io/addons/prometheus/`, Nginx started crashing and entered `CrashLoopBackOff` state, here's the pod log:

```
-------------------------------------------------------------------------------
NGINX Ingress controller
  Release:    0.11.0
  Build:      git-9d0ce7c
  Repository: https://github.com/kubernetes/ingress-nginx
-------------------------------------------------------------------------------

I0319 11:38:39.327566       5 flags.go:154] Watching for ingress class: nginx
I0319 11:38:39.380245       5 main.go:183] Creating API client for https://10.3.0.1:443
I0319 11:38:40.111339       5 main.go:227] Running in Kubernetes Cluster version v1.9 (v1.9.3) - git (clean) commit d2835416544f298c919e2ead3be3d0864b52323b - platform linux/amd64
I0319 11:38:40.141300       5 main.go:86] validated ingress/default-backend as the default backend
I0319 11:38:40.840336       5 stat_collector.go:77] starting new nginx stats collector for Ingress controller running in namespace  (class nginx)
I0319 11:38:40.840662       5 stat_collector.go:78] collector extracting information from port 18080
I0319 11:38:40.853289       5 nginx.go:278] starting Ingress controller
I0319 11:38:41.960304       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"ingress", Name:"kube-lego-nginx", UID:"3f34f59d-2ad7-11e8-aaee-06fc97112e4a", APIVersion:"extensions", ResourceVersion:"90302", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress ingress/kube-lego-nginx
I0319 11:38:41.960453       5 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"kub-test-5682440", Name:"production-auto-deploy", UID:"3f1e013b-2ad7-11e8-aaee-06fc97112e4a", APIVersion:"extensions", ResourceVersion:"90301", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress kub-test-5682440/production-auto-deploy
I0319 11:38:42.053972       5 store.go:614] running initial sync of secrets
I0319 11:38:42.055654       5 backend_ssl.go:68] adding secret kub-test-5682440/production-auto-deploy-tls to the local store
I0319 11:38:42.055758       5 nginx.go:300] starting NGINX process...
I0319 11:38:42.057092       5 leaderelection.go:174] attempting to acquire leader lease...
I0319 11:38:42.062049       5 controller.go:171] backend reload required
I0319 11:38:42.062156       5 stat_collector.go:34] changing prometheus collector from  to default
I0319 11:38:42.095268       5 leaderelection.go:184] successfully acquired lease ingress/ingress-controller-leader-nginx
I0319 11:38:42.121277       5 status.go:192] new leader elected: nginx-ingress-controller-dp8vv
I0319 11:39:04.865312       5 main.go:152] Received SIGTERM, shutting down
I0319 11:39:04.868358       5 nginx.go:359] shutting down controller queues
I0319 11:39:04.869835       5 status.go:115] updating status of Ingress rules (remove)
E0319 11:39:04.879699       5 controller.go:176] unexpected failure restarting the backend:
signal: terminated
W0319 11:39:04.887190       5 queue.go:113] requeuing , err signal: terminated
I0319 11:39:04.897838       5 controller.go:171] backend reload required
I0319 11:39:12.641221       5 status.go:134] removing address from ingress status ([])
I0319 11:39:12.659996       5 nginx.go:367] stopping NGINX process...
```

Then I ran:

```kubectl delete --all deployments --namespace=monitoring```

And Nginx restarted without any problems.

### Desired Behavior

Be able to get Nginx Ingress to work with Prometheus.

### Steps to Reproduce

- Install the Nginx Ingress addon on DigitalOcean
- Install Prometheus addon on DigitalOcean
- Install Grafana addon on DigitalOcean
- The problem here is that the problem did not started immediately after I did the previous steps, I went to sleep and then a few hours later I checked my cluster and got this:
```
NAMESPACE          NAME                                        READY     STATUS             RESTARTS   AGE
ingress            nginx-ingress-controller-dp8vv              0/1       CrashLoopBackOff   106        17
```

If you guys need any help, please let me know.

**Comment by dghubble** [comment] 2018-03-22 03:15
I can't reproduce your problem. I've had a Digital Ocean cluster running the nginx-ingress/digital-ocean, prometheus, and grafana addons for two days.

You may need to dig into your logs a bit more and investigate your setup.

**Comment by dghubble** [comment] 2018-03-23 04:53
Are you still seeing this? I've had no problems, but perhaps try with the more recent nginx-ingress and prometheus versions since each recently updated.

**Comment by felipe-augusto** [comment] 2018-03-24 22:28
I will try again @dghubble, then I can give you some feedback about this

**Comment by dghubble** [comment] 2018-03-27 04:20
Ok, I'm closing for now. If you can reproduce it, feel free to re-open or ask on IRC.

**Closed by dghubble** 2018-03-27 04:20 UTC
Labels: status/needs-details
