### ISSUE TITLE
typhoon kubernetes "bootkube" start error

### ISSUE THREAD

**Issue by fatihkose** [poseidon/typhoon#167] opened 2018-03-23 21:50 UTC
## Bug
```
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec): Connecting to remote host via SSH...
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec):   Host: 35.188.204.252
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec):   User: core
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec):   Password: false
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec):   Private key: false
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec):   SSH Agent: true
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec):   Checking Host Key: false
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec): Connected!
module.google-cloud-yavin.null_resource.bootkube-start: Still creating... (10s elapsed)
module.google-cloud-yavin.null_resource.bootkube-start: Still creating... (20s elapsed)
module.google-cloud-yavin.null_resource.bootkube-start: Still creating... (30s elapsed)
module.google-cloud-yavin.null_resource.bootkube-start: Still creating... (40s elapsed)
module.google-cloud-yavin.null_resource.bootkube-start: Still creating... (50s elapsed)
module.google-cloud-yavin.null_resource.bootkube-start: Still creating... (1m0s elapsed)
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec): Job for bootkube.service failed because the control process exited with error code.
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec): See "systemctl  status bootkube.service" and "journalctl  -xe" for details.

Error: Error applying plan:

1 error(s) occurred:

* module.google-cloud-yavin.null_resource.bootkube-start: Remote command exited with error: Process exited with status 1

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Environment

* Platform: google-cloud
* OS: container-linux
* Terraform: Terraform v0.11.5
* Plugins: + provider.ct (unversioned)
+ provider.google v1.6.0
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0

### Problem

When trying to run 'terraform apply' command I'm receiving the following error:

```
> Error: Error applying plan:
> 
> 1 error(s) occurred:
> 
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec): Job for bootkube.service failed because the control process exited with error code.
module.google-cloud-yavin.null_resource.bootkube-start (remote-exec): See "systemctl  status bootkube.service" and "journalctl  -xe" for details.
```
### Desired Behavior

It should have started bootkube service

**Comment by dghubble** [comment] 2018-03-23 22:27
You haven't shown the actual logs. Please run the commands it tells you to run. `systemctl status bootkube` and `journalctl -f -u bootkube`.

**Comment by fatihkose** [comment] 2018-03-23 23:48
core@yavin-controller-0 ~ $ systemctl  status bootkube.service

```
● bootkube.service - Bootstrap a Kubernetes cluster
   Loaded: loaded (/etc/systemd/system/bootkube.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2018-03-23 23:42:34 UTC; 2min 43s ago
  Process: 1174 ExecStart=/opt/bootkube/bootkube-start (code=exited, status=1/FAILURE)
 Main PID: 1174 (code=exited, status=1/FAILURE)

Mar 23 23:42:28 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]:   Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]: [  117.753381] bootkube[6]: Starting temporary bootstrap control plane...
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]: [  117.754465] bootkube[6]: Error: lstat /assets/tls: no such file or directory
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]: [  117.754895] bootkube[6]: Tearing down temporary bootstrap control plane...
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]: [  117.755347] bootkube[6]: Error: lstat /assets/tls: no such file or directory
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]: [  117.755807] bootkube[6]: Error: lstat /assets/tls: no such file or directory
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal bootkube-start[1174]: [  117.756239] bootkube[6]: lstat /assets/tls: no such file or directory
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal systemd[1]: bootkube.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal systemd[1]: bootkube.service: Failed with result 'exit-code'.
Mar 23 23:42:34 yavin-controller-0.c.fetchsome-test-198717.internal systemd[1]: Failed to start Bootstrap a Kubernetes cluster.
core@yavin-controller-0 ~ $ 

```
core@yavin-controller-0 ~ $ journalctl  -xe

```
Mar 23 23:46:44 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:44.026848     885 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:Netw
Mar 23 23:46:44 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:44.046842     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:44 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:44.048971     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:44 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:44.049164     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:44 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:44.695502 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:45 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:45.049789     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:45 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:45.050467     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:45 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:45.052104     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:45 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:45.698295 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:46 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:46.075500     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:46 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:46.076169     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:46 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:46.076318     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:46 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:46.701215 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:47 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:47.078804     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:47 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:47.079466     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:47 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:47.079598     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:47 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:47.703667 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:48.081812     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:48.082613     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:48.083711     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: I0323 23:46:48.274977     885 kubelet_node_status.go:273] Setting node annotation to enable volume controller atta
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: I0323 23:46:48.296810     885 kubelet_node_status.go:82] Attempting to register node yavin-controller-0.c.fetchsom
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:48.298817     885 kubelet_node_status.go:106] Unable to register node "yavin-controller-0.c.fetchsome-
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:48.712728 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:48 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:48.829968     885 eviction_manager.go:238] eviction manager: unexpected err: failed to get node info: 
Mar 23 23:46:49 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: W0323 23:46:49.028389     885 cni.go:171] Unable to update cni config: No networks found in /etc/kubernetes/cni/ne
Mar 23 23:46:49 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:49.028813     885 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:Netw
Mar 23 23:46:49 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:49.084652     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:49 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:49.085300     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:49 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:49.086903     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:49 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:49.715314 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:50 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:50.087688     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:50 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:50.088409     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:50 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:50.090009     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:50 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:50.718359 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:50 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:50.836428     885 event.go:209] Unable to write event: 'Post https://yavin.beta.fetchsome.com:443/api/
Mar 23 23:46:51 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:51.116796     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:51 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:51.117491     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:51 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:51.117727     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:51 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:51.721175 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:52 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:52.119815     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:52 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:52.120514     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:52 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:52.122119     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:52 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:52.723691 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:53 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:53.123132     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:53 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:53.123858     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:53 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:53.124012     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:53 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:53.751587 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:54 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: W0323 23:46:54.030126     885 cni.go:171] Unable to update cni config: No networks found in /etc/kubernetes/cni/ne
Mar 23 23:46:54 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:54.030451     885 kubelet.go:2120] Container runtime network not ready: NetworkReady=false reason:Netw
Mar 23 23:46:54 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:54.126221     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:54 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:54.126865     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:54 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:54.127034     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:54 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:54.754142 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:55.128837     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to li
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:55.129524     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:471: Failed to list *v1.S
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:55.131010     885 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:480: Failed to list *v1.N
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: I0323 23:46:55.299165     885 kubelet_node_status.go:273] Setting node annotation to enable volume controller atta
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: I0323 23:46:55.321829     885 kubelet_node_status.go:82] Attempting to register node yavin-controller-0.c.fetchsom
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal kubelet-wrapper[885]: E0323 23:46:55.324724     885 kubelet_node_status.go:106] Unable to register node "yavin-controller-0.c.fetchsome-
Mar 23 23:46:55 yavin-controller-0.c.fetchsome-test-198717.internal etcd-wrapper[1697]: 2018-03-23 23:46:55.756613 W | pkg/netutil: failed resolving host yavin-etcd0.beta.fetchsome.com:2380 (lookup yavin-
lines 1033-1093/1093 (END)

```

**Comment by dghubble** [comment] 2018-03-24 18:38
Ok. Is etcd healthy (systemctl status etcd-member)? Did `yavin-etcd0.beta.fetchsome.com` get created and resolve to the controller's internal IP?

Shot in the dark, but be sure you're filling out the `dns_zone` and `dns_zone_name` correctly https://typhoon.psdn.io/google-cloud/#dns-zone. Typhoon test clusters on GCP create fine and there haven't been changes in this area in a while.

**Comment by iMerica** [comment] 2018-03-24 20:13
Looks like I'm having a similar issue.

**Comment by fatihkose** [comment] 2018-03-24 23:09
The first answer is; yes it does as follows:

```
devops@yavin-controller-0 ~ $ dig yavin-etcd0.beta.fetchsome.com.
; <<>> DiG 9.10.2-P4 <<>> yavin-etcd0.beta.fetchsome.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41420
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;yavin-etcd0.beta.fetchsome.com.        IN      A
;; ANSWER SECTION:
yavin-etcd0.beta.fetchsome.com. 299 IN  A       10.128.0.2
;; Query time: 3 msec
;; SERVER: 169.254.169.254#53(169.254.169.254)
;; WHEN: Sat Mar 24 23:05:42 UTC 2018
;; MSG SIZE  rcvd: 75

```

GCP DNS records:

```

  | DNS name | Type | TTL (seconds) | Data |  
-- | -- | -- | -- | -- | --
  | beta.fetchsome.com. | A | 180 | 35.225.90.218 |  
  | beta.fetchsome.com. | NS | 21600 | ns-cloud-a1.googledomains.com.ns-cloud-a2.googledomains.com.ns-cloud-a3.googledomains.com.ns-cloud-a4.googledomains.com. |  
  | beta.fetchsome.com. | SOA | 21600 | ns-cloud-a1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200 300 |  
  | yavin.beta.fetchsome.com. | A | 300 | 35.225.23.55 |  
  | yavin-etcd0.beta.fetchsome.com. | A | 300 | 10.128.0.2 |  

```

**Comment by dghubble** [comment] 2018-03-25 00:49
Well, you're both erroring at a stage where bootkube assets are copied to a controller node and bootkube can't find its TLS assets (`Error: lstat /assets/tls: no such file or directory`). You're on different cloud providers and probably new-comers, so that narrows possibilities some.

On the first controller, do you have files in those directories?

```
$ ls /opt/bootkube/assets/                                           
auth  bootstrap-manifests  manifests  tls      
```

I do see you're both using very newest `terraform-provider-tls` plugin. Perhaps pin that to v1.0.0 instead.

**Comment by dghubble** [comment] 2018-03-25 01:16
Don't think its the plugin or Terraform version. Works fine for me.

```
terraform version        
Terraform v0.11.5      
+ provider.ct (unversioned)                    
+ provider.digitalocean v0.1.3                 
+ provider.local v1.1.0                        
+ provider.null v1.0.0 
+ provider.template v1.0.0                     
+ provider.tls v1.1.0  
```

```
module "nyc3-do-nemo" {
  source = "git::https://github.com/poseidon/typhoon//digital-ocean/container-linux/kubernetes?ref=v1.9.6"

  providers = {
    digitalocean = "digitalocean.default"
    local        = "local.default"
    null         = "null.default"
    template     = "template.default"
    tls          = "tls.default"
  }

  # Digital Ocean
  cluster_name = "nemo"
  region       = "nyc3"
  dns_zone     = "digital-ocean.dghubble.io"

  # configuration
  ssh_fingerprints = "${var.ssh_fingerprints}"
  asset_dir        = "/home/dghubble/vault/clusters/nemo"

  # optional
  worker_count = 2
}
```

**Comment by fatihkose** [comment] 2018-03-25 17:58
I was using typhoon in Digital Ocean without any problem. But on GCP it is not the same.

One important thing I missed to say, I changed provider version from 1.2 to 1.6 since I was getting the following error:

```
[devop@fs-it-server typhoon-server]$ terraform init
Initializing modules...
- module.google-cloud-yavin
- module.google-cloud-yavin.bootkube
- module.google-cloud-yavin.controllers
- module.google-cloud-yavin.workers

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...

No provider "google" plugins meet the constraint "1.2,~> 1.6".

The version constraint is derived from the "version" argument within the
provider "google" block in configuration. Child modules may also apply
provider version constraints. To view the provider versions requested by each
module in the current configuration, run "terraform providers".

To proceed, the version constraints for this provider must be relaxed by
either adjusting or removing the "version" argument in the provider blocks
throughout the configuration.

```
With the new config, I came to the final point except for "bootkube start" error.

Actually this config is coming from official website https://typhoon.psdn.io/google-cloud/. I chnagted to this

```
provider "google" {
  version = "1.2"
  #version = "1.6"
  alias   = "default"
  credentials = "${file("~/.config/google-cloud/terraform.json")}"
  project     = "fetchsome-test-199008"
  region      = "us-central1"
}

```
How to resolve this problem, maybe this caused the problem?

Thanks.

**Comment by dghubble** [comment] 2018-03-25 18:35
The Typhoon module is (correctly) enforcing that you use the terraform-provider-google 1.6 or never. I enforce the minimum version whenever features are added that [necessitate it](https://github.com/poseidon/typhoon/blob/master/CHANGES.md#google-cloud-1). The docs example that still mentions 1.2 is out of date (I'll fix).

I use the terraform-provider-google 1.6 as well and haven't had a problem, so that shouldnt be the cause.

**Comment by dghubble** [comment] 2018-03-25 18:46
If you delete the cluster ([basically](https://typhoon.psdn.io/topics/maintenance/#cloud) comment out the module, `terraform apply`, and uncomment it again) can you reproduce this every time? If so, can you list the /opt/bootkube/assets like I mentioned above? At least that could narrow it down to a Terraform copy issue.

I'm running out of theories here - everything is version pinned so we should all be doing identical steps. And you can't reproduce @iMerica's issue on Digital Ocean. Hmm.

**Comment by dghubble** [comment] 2018-03-25 18:53
Can you try going back to Terraform v0.11.3 or v0.11.4? I see some suspect changes to remote commands (the step Typhoon has to use to bootstrap the control plane) added between 0.11.4 and 0.11.5.

**Comment by veliaho** [comment] 2018-03-30 18:33
Any solution for this? I have errors on logs that @fatihkose already listed.

`o$ terraform version
Terraform v0.11.5
+ provider.ct (unversioned)
+ provider.digitalocean v0.1.3
+ provider.local v1.1.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0
`

**Comment by dghubble** [comment] 2018-03-30 18:45
I've never been able to reproduce it. Look at the /opt/bootkube/assets and try to investigate why those assests aren't present for you.

**Comment by ainformatico** [comment] 2018-04-01 22:31
I had the same issue `Error: lstat /assets/tls: no such file or directory` and just managed to fixed it.
In my config I had:

```
asset_dir = "~/.secrets/clusters/nemo"
```

I fixed it by expanding the whole path:

```
asset_dir = "/home/ainformatico/.secrets/clusters/nemo"
```

@fatihkose @veliaho can you check the expanded path is used? or the `asset_dir` exists and has the correct permissions?

**Comment by veliaho** [comment] 2018-04-02 10:13
Thank you @ainformatico. The asset_dir was probably the issue also for me. I already had deleted my project but I remember having relative path on asset_dir. I just made everything from scratch and it worked fine.

**Comment by dghubble** [comment] 2018-04-04 03:15
Nice, thanks! That would certainly cause it @ainformatico - Terraform doesn't understand bash's `~`.

For future folks who see a bootkube start failure and run `journalctl -u bootkube` to find `Error: lstat /assets/tls: no such file or directory` - that indicates Terraform didn't copy the secret materials onto the controller, which is required to bootstrap. Possible causes:

* `asset_dir` points to the wrong location or is incorrect (`~` isn't valid)
* Assets aren't present in the assets directory (e.g. got deleted)
* Future Terraform version changes how remote_exec works for the one-time secrets copy

Docs already show absolute paths so there are no changes to be made. Closing.

**Closed by dghubble** 2018-04-04 03:15 UTC

**Comment by GrantKlassy** [comment] 2018-06-08 20:00
+1 to asset_dir requiring no slash in the terraform config. If the slash is included the tls subdir doesn't get copied, subsequently causing `lstat /assets/tls: no such file or directory`.
