### ISSUE TITLE
Integrate digitalocean-cloud-controller-manager for exposing Services with an external IP. 

### ISSUE THREAD

**Issue by IAlwaysBeCoding** [poseidon/typhoon#118] opened 2018-02-06 17:46 UTC
At the moment, kubernetes Services can't really expose an IP outside the cluster because DigitalOcean is not a supported cloud provider.

It would be lovely to be able to integrate this:https://github.com/digitalocean/digitalocean-cloud-controller-manager into typhoon so we could use their LoadBalancer and expose services to an external IP.

**Comment by IAlwaysBeCoding** [comment] 2018-02-10 03:03
So, I've been having problems with the firewall that is automatically created with the cluster. Using the digitalocean-cloud-controller-manager fails to connect the nodes to the loadbalancer when this firewall is enabled on the nodes.

Therefor it is not possible to create a service outside digitalocean with this firewall. I've tried countless of times using the digitalocean-cloud-controller-manager and it wont' work unless I take out the firewall.

**Comment by dghubble** [comment] 2018-02-10 03:24
At the moment, Digital Ocean's offering provides features you can get in cleaner ways already. If your root aim is to expose services, you can use the Nginx Ingress controller addon for TCP, UDP, and HTTP/HTTPS services. https://github.com/poseidon/typhoon/blob/master/docs/addons/ingress.md#digital-ocean. This avoids the need for a component to hold cloud-provider credentials and avoids the need to allocate a load balancer per service (avoid type LoadBalancer).

In the future, if the controller manager adds support for block storage attachment / detachment, we'll evaluate it and consider including it in an opt-in, addon way.

**Comment by dghubble** [comment] 2018-02-10 03:29
Its worth noting that the Digital Ocean platform is the only Typhoon platform that doesn't setup an Ingress Load Balancer on behalf of users (hence the Daemonset and CNAME approach used in docs). Originally this was done to keep DO dirt cheap since its popular among developers. We may need to re-evaluate that.

**Comment by IAlwaysBeCoding** [comment] 2018-02-10 22:05
@dghubble Thank you very but then how exactly would that allow me to deploy multiple services that use the port 80 for my workers FQDN?

If I understand your reply correctly, you want me to create CNAME for app1.nemo.mysite.com that will link to nemo-workers.mysite.com ? If all of my workers have the nemo-workers.mysite.com as their FQDN, then how would they be able to accommodate for more than 1 service?

I understood that with a load balancer you get a EXTERNAL_IP that can be used per service, how would this work with your proposed solution if the EXTERNAL_IP is technically the same for all of the workers.

With a loadbalancer I noticed that it redirected the traffic to the exact port the service was located at. So it was something like port 31480. It worked without the firewall, however it was a $20 dollar a month or 3 cents an hour per service, which adds up for every service I want exposed.

**Comment by dghubble** [comment] 2018-02-10 23:11
Ingress supports SNI, there is no problem running multiple sites. First, you need to write an Ingress resource and fill out the `host` section correctly, as usual. https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

On the infrastructure side, your sole responsibility is to ensue packets are routed to Ingress controller pods. On Digital Ocean, the cheapest way is to run the Nginx Ingress controller as a DaemonSet across workers as [described](https://github.com/poseidon/typhoon/blob/master/docs/addons/ingress.md#digital-ocean). The `cluster-workers.mysite.com` DNS records resolve to workers (and thus Ingress controllers) so "for each application, add a CNAME record resolving to the worker(s) DNS record".

```
app1.domain.com -> CNAME cluster-workers.domain.com
app2.domain.com -> CNAME cluster-workers.domain.com
```

On other platforms (AWS, Google Cloud, perhaps future DO) that create a load balancer for Ingress (with one IP), you'd create a DNS record for each app to that IP.

**Comment by dghubble** [comment] 2018-02-11 00:03
Ingress supports SNI, so multiple sites should not be an issue. Create an Ingress resource for each application and fill out the `host` section, as usual. https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

On the infrastructure side, your sole responsibility is to ensure packets destined for app1, app2, etc. reach an Ingress controller pod. On Digital Ocean, the cheap way to deploy the Nginx Ingress controller as a DaemonSet across workers as [described](https://github.com/poseidon/typhoon/blob/master/docs/addons/ingress.md#digital-ocean) and make use of the DNS record `cluster-workers.domain.com` which resolves to a worker (and thus an Ingress controller). Then, "for each application, add a CNAME record resolving to the worker(s) DNS record".

```
app1.domain.com -> CNAME cluster-workers.domain.com
app2.domain.com -> CNAME cluster-workers.domain.com
app3.somedomain.com -> CNAME cluster-workers.domain.com
```

On other platforms (AWS, Google), a load balancer is created which has a single IP and you'd do something similar, creating an A record for each app, that resolves to the shared load balancer IP.

Edit: I've double checked, there is no trouble running multiple HTTPS sites on DO clusters.

**Comment by dghubble** [comment] 2018-02-15 22:56
Was this helpful or have you chosen to take another route to setup Ingress?

**Comment by dghubble** [comment] 2018-02-22 07:39
Closing this out. Digital Ocean with the Ingress addon is working as intended. That's the recommended way to expose services.

**Closed by dghubble** 2018-02-22 07:39 UTC
Labels: addons, status/maybe-later

**Comment by captainjapeng** [comment] 2018-02-25 05:29
Hi, I don't know if this the right place to ask but I'm having trouble setting up my DNS using the nginx ingress.

`*.domain.com -> CNAME cluster-workers.domain.com` is working just fine, but I'm having difficulties settings up the DNS for the root domain. `domain.com` gets `Could not resolve host` on curl

**Comment by captainjapeng** [comment] 2018-02-25 05:49
I solved it by adding `@ -> A xxx.xxx.xxx.xxx`. Where the IP is set same with the one on `cluster-workers.domain.com`. Thanks anyways
